# For more information: https://laravel.com/docs/sail
version: "3"
services:
  caddy:
    image: caddy
    restart: unless-stopped
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - .:/srv
    ports:
      - 80:80
      - 443:443

  php:
    build: ./docker
    restart: unless-stopped
    working_dir: /srv
    volumes:
      - .:/srv
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - 54321:5432
